from typing import Protocol
from uuid import UUID

from topicgate.core.models.diagnostic_profile import DiagnosticProfile


class DiagnosticProfileRepository(Protocol):
    def list_for_broker(self, broker_id: UUID) -> tuple[DiagnosticProfile, ...]: ...
    def get(self, profile_id: UUID, *, transaction: object | None = None) -> DiagnosticProfile | None: ...
    def create(self, profile: DiagnosticProfile, *, transaction: object | None = None) -> DiagnosticProfile: ...
    def update(self, profile: DiagnosticProfile, *, transaction: object | None = None) -> DiagnosticProfile: ...
    def delete(self, profile_id: UUID, *, transaction: object | None = None) -> None: ...
