from datetime import datetime
from typing import Protocol
from uuid import UUID

from topicgate.core.models.history_retention import HistoryPruneResult, HistoryRetentionPolicy, HistoryUsage


class HistoryRetentionStore(Protocol):
    def get_policy(self) -> HistoryRetentionPolicy: ...
    def set_policy(self, policy: HistoryRetentionPolicy) -> None: ...
    def usage(self, broker_id: UUID | None = None) -> HistoryUsage: ...
    def prune(self, now: datetime) -> HistoryPruneResult: ...
