from typing import Protocol
from uuid import UUID

from topicgate.core.models.history_recording import HistoryRecordingStatus


class HistoryRecordingStore(Protocol):
    def enabled_brokers(self) -> tuple[UUID, ...]: ...
    def set_enabled(self, broker_id: UUID, enabled: bool) -> None: ...
    def begin_session(self, broker_id: UUID, session_id: UUID) -> HistoryRecordingStatus: ...
    def checkpoint(
        self, session_id: UUID, status: HistoryRecordingStatus, *, closed: bool = False,
    ) -> None: ...
    def status(self, broker_id: UUID) -> HistoryRecordingStatus: ...
